Models/Company.cs
namespace SWMGApp.Models
{
    public class Company
    {
        public int CompanyId { get; set; }
        public string Name { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace SWMGApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Help.cs
namespace SWMGApp.Models
{
    public class Help
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Datetime { get; set; }
        public string Msg { get; set; }
    }
}

Models/Industry.cs
namespace SWMGApp.Models
{
    public class Industry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AvgWage { get; set; }
        public string minEducation { get; set; }
        public List<Company> Companies { get; set; }
    }
}

Models/Job.cs
namespace SWMGApp.Models
{
    public class Job
    {
        public int JobId { get; set; }
        public string JobName { get; set; }
        public Industry Industry { get; set; }
        public int AvgWage { get; set; }
    }
}

Models/Newsletter.cs
namespace SWMGApp.Models
{
    public class Newsletter
    {
        public int Id { get; set; }
        public string Email { get; set; }
    }
}

Controllers/DataController.cs
using Microsoft.AspNetCore.Mvc;
using SWMGApp.Data;
using SWMGApp.Models;

namespace SWMGApp.Controllers
{
    public class DataController : Controller
    {
        public IWebsiteRepo repo;
        public DataController(IWebsiteRepo r)
        {
            repo = r;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Industry()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string industryType)
        {
            var loadedModel = new Industry();
            if (industryType == "Bio Science")
            {
                loadedModel = repo.GetIndustry(1);
            }
            
            else if(industryType == "Nutrition")
            {
                loadedModel = repo.GetIndustry(2);
            }
            else if(industryType == "Technology")
            {
                loadedModel = repo.GetIndustry(3);
            }
            else if (industryType == "Wood Working")
            {
                loadedModel = repo.GetIndustry(4);
            }
            else if (industryType == "Healthcare")
            {
                loadedModel = repo.GetIndustry(5);
            }
            else if (industryType == "Sports")
            {
                loadedModel = repo.GetIndustry(6);
            }


            return RedirectToAction("Industry", loadedModel); 
        }
    }
}

Controllers/HomeController.cs
using SWMGApp.Data;
using SWMGApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace SWMGApp.Controllers
{
    public class HomeController : Controller
    {
        IWebsiteRepo repo;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IWebsiteRepo r)
        {
            _logger = logger;
            repo = r;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult SWMG()
        {
            return View();
        }

        public IActionResult NewsLetter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string email)
        {
            Newsletter model = new Newsletter();
            model.Email = email;
            repo.StoreNewsletter(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Newsletter(string email)
        {
            Newsletter model = new Newsletter();
            model.Email = email;
            repo.StoreNewsletter(model);
            return RedirectToAction("Index");
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Help()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Help(string name, string email, string msg)
        {
            Help h = new Help();
            h.Name = name;
            h.Email = email;
            h.Msg = msg; 
            h.Datetime = "123"; //this needs actually implemented to get the real datetime
            repo.StoreHelp(h);
            return View();
        }


   /*     [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }*/
    }
}

Controllers/JobsController.cs
using Microsoft.AspNetCore.Mvc;
using SWMGApp.Data;
using SWMGApp.Models;


namespace SWMGApp.Controllers
{
    public class JobsController : Controller
    {
        public IWebsiteRepo repo;
        public JobsController( IWebsiteRepo r)
        {
            repo = r;
        }
        public IActionResult Index()
        {
            var model = repo.GetJobs();
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(string job, string industry)
        {
            List<Job> jobs = repo.GetJobs();
            List<Job> sortedJobs = new List<Job>();
            if (job != null && industry != null) 
            {
                sortedJobs = (from n in repo.GetJobs()
                              where n.JobName == job &&
                              n.Industry.Name == industry
                              select n).ToList();
            }
            else if (job != null && industry == null)
            {
                sortedJobs = (from n in repo.GetJobs()
                              where n.JobName == job
                              select n).ToList();
            }
            else if (job == null && industry != null)
            {
                sortedJobs = (from n in repo.GetJobs()
                              where n.Industry.Name == industry
                              select n).ToList();
            }

            return View(sortedJobs);
        }

    }
}

Views/Data/Index.cshtml
<div>
    <h1>Data</h1>
</div>

<div>
    <p> Our platform is a hub of meticulously curated data, offering a comprehensive analysis of economic trends, employment opportunities, and industry forecasts.</p>
    <div>
        <h1>Lane County Economy Graph Here</h1>
        <p>Possibly make this graph interactive </p>
    </div>
    <div>
        <h1>Industries</h1>
        <p>
            Explore the Industries offered in Lane County and
            their status. Find what’s best for you!
        </p>
    </div>
    <div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Bio Science"/>
                <input type="submit" value="Bio Science"/>
            </form>
        </div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Nutrition" />
                <input type="submit" value="Nutrition" />
            </form>
        </div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Technology" />
                <input type="submit" value="Technology" />
            </form>
        </div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Wood Working" />
                <input type="submit" value="Wood Working" />
            </form>
        </div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Healthcare" />
                <input type="submit" value="Healthcare" />
            </form>
        </div>
        <div>
            <form method="post">
                <input hidden name="industryType" value="Sports" />
                <input type="submit" value="Sports" />
            </form>
        </div>
    </div>
</div>

Views/Data/Industry.cshtml
@Model 

Views/Home/About.cshtml
<div>
    <h1>About Lane County</h1>
</div>

<div>
    <div>
        <p>Lane County stands among the 36 counties in the state of Oregon, USA. According to the 2023 census, its population reached 392,349, ranking it as the fourth-most populous county in Oregon. Eugene, the second-largest city in the state, serves as the county seat. The county is named in tribute to Joseph Lane, who held the distinction of being Oregon's inaugural territorial governor.</p>
    </div>
    <div>
        <P>Eugene is home to the University of Oregon, where over 22 thousand students from over the county receive higher education. It offers a tier 1 program as a National Public Research institution. Its ranked in the top 49th Public School in the Nation. GO DUCKS!</P>
    </div>
    <div>
        <p>Housing costs in Eugene are around 30% higher than the national average, which puts the average price of a home around $400,0001. The median sale price of a home in Eugene was $522K last month, up 5.5% since last year. The median sale price per square foot in Eugene is $307, up 2.7% since last year. For a single adult in Eugene, the total housing costs, groceries, childcare services, commuting, medical services, taxes, and other needs are $35,551 per year.</p>
    </div>
</div>

Views/Home/Data.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Help.cshtml
<div>
    <h1>Help ?</h1>
</div>

<div>
    <p>We are here to help you. Please let us know what we can help you with and we will contact you as soon as possible!</p>
    <form method="post">
        <input type="text" name="name" value="Enter name..."/><br />
        <input type="text" name="email" value="Enter email address..." /><br />
        <input type="text" name="msg" value="Tell us what your problem is" /><br />
        <input type="submit" value="Submit" /><br />
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<body>
    <div class="container">
        <div class="row">

            <!-- Card 1 -->
            <div class="col-md-6">
                <div class="card custom-card">
                    <img src="./files/Gradient.png" style="width: 100%; height:400px;" class="card-img" alt="Placeholder Image">
                    <div class="card-img-overlay d-flex align-items-center justify-content-center">
                        <p class="custom-h1 text-center text-white">
                            Explore the dynamic landscape of career opportunities in Lane County by understanding economic trends. Join us in building a stronger Lane County economy by empowering individuals to make strategic career choices that align with the region's economic trajectory.
                        </p>
                    </div>
                </div>
            </div>

            <!-- Card 2 -->
            <div class="col-md-6">
                <div class="card custom-card">
                    <img src="./files/Index.gif" style="width: 100%; height: 400px;" class="card-img" alt="Placeholder Image">
                    <div class="card-img-overlay">
                        <h1 class="card-title custom-h1">Empowering Futures</h1>
                        <form class="custom-form" method="post">
                            <label for="email">Get Started...</label>
                            <input type="text" class="form-control" placeholder="Enter Your Email Address Here..." />
                            <input type="submit" class="btn btn-primary mt-2" value="Enter" />
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <p class="centered-text mw-50">
        By providing comprehensive insights into economic trends, we empower the public, educators, and industry professionals to collaborate seamlessly. Explore our platform to gain a deeper understanding of Lane County's economic landscape, ensuring that together, we can make decisions that not only secure high-wage employment but also strengthen the fabric of our community.
    </p>
    <div class="d-flex justify-content-center">
        <div class="clickable-picture">
            <a asp-area="" asp-controller="Data" asp-action="Index">
                <img src="./files/Data.png" alt="Data">
            </a>
        </div>
        <br />



        <div class="clickable-picture">
            <a asp-area="" asp-controller="Home" asp-action="Help">
                <img src="./files/Help.png" alt="Help">
            </a>
        </div>


        <div class="clickable-picture">
            <a asp-area="" asp-controller="Jobs" asp-action="Index">
                <img src="./files/ALC.png" alt="Find What's Right">
            </a>
        </div>

        <div class="clickable-picture">
            <a asp-area="" asp-controller="Home" asp-action="About">
                <img src="./files/FWR.png" alt="About Lane County">
            </a>
        </div>
    </div>
   
    



    <div class="text-center mt-4">
        <h1>
            <a class="btn btn-outline-primary btn-lg" asp-area="" asp-controller="Home" asp-action="Newsletter">
                News Letter
                <i class="bi bi-arrow-right"></i>
            </a>
        </h1>
        <p class="mt-3">
            Our newsletter is your key to unlocking valuable information including high-demand industries, emerging opportunities, and expert advice. Delivered regularly to your inbox,
        </p>
          <p>  it's the perfect resource for those looking to make informed decisions that drive success.
        </p>
    </div>
</body>
   

Views/Home/Job.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Jobs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Home/Newsletter.cshtml
<body class="newsletter">
    <div>
        <h1>
            News Letter
        </h1>
    </div>
    
    <div class="Rain">
        <h2>Oregon RAIN</h2>
        <p>
            Fueled by a plethora of groundbreaking ideas emerging from the University of Oregon and Oregon State University, coupled with a pressing need for capital to fuel the growth of nascent startups stemming from these concepts, Oregon RAIN emerged. This public-private partnership is dedicated to facilitating connections between entrepreneurs in Lane, Linn, Lincoln, and Benton counties, linking them with vital resources to propel early-stage companies to new heights.
        </p>
    </div>

    <div class="Work">
        <h2>Lane Workforce</h2>
        <p>
            The Lane Workforce Partnership has undertaken the mission of readying individuals for employment in a rapidly evolving economy. Over the past year, the organization established ambitious objectives, and not only are they meeting these goals, but they are also surpassing them in ways that extend beyond measurable outcomes. As the officially designated Workforce Investment Board for Lane County, Oregon, the board assumes the responsibility of strategically allocating federal funds through targeted investments within the community. In alignment with its mission, Lane Workforce Partnership (LWP) continues to operate with a commitment to fostering economic growth and workforce development in the region.
        </p>
    </div>

    <div class="county">
        <h2>Connected Lane County</h2>
        <p>
            In the heart of our community, Connected Lane County stands as a beacon of collaboration and commitment to the youth's educational journey. As a non-profit organization, we wholeheartedly support childhood partners and work hand-in-hand with local school districts, institutions of higher education, the local workforce board, and industry innovators. Thaks to this organization, hundreds of youths in our community benefit form higher learning education. Support Connected Lane County here!
        </p>
    </div>

    <div class="card shadow-sm w-75 container mt-5 card text-center mb-3">
        <form method="Post">
            <div class="card-body shadow-lg">
                <label for="Email">If you would like the join the Email:</label>
                <input id="Email" name="email" />
                <button type="submit" class="btn btn-primary">Sign Up.</button>
            </div>
        </form>
    </div>
</body>

Views/Home/SWMG.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<div class="SWMG">
  
    <h1>@ViewData["Title"]</h1>

    <p>This webpage is sponsered by the shadow government</p>

    <video src="~/files/ShadowWizardMoneyGang.mp4" autoplay width="75%"></video>
</div>

Views/Jobs/Index.cshtml
@model List<Job>
<div>
    <h1>Job Navigator</h1>
</div>

<div class="row g-3">
    <form method="post"
        <div class="form-group col-md-6">
            <br />
        <input type="text" name="job" />
       
        </div>
       <br />
        <div class="form-group col-md-6">
            <select class="form-group col-md-6" id="industry" name="industry">
                <option>Industry</option>
                <option>Bio Science</option>
                <option>Nutrition</option>
                <option>Technology</option>
                <option>Wood Working</option>
                <option>Healthcare</option>
                <option>Sports</option>
            </select>
            </div>
       @*  <select>
            <option>Filter</option>
            <option>heres an option</option>
            <option>heres an option</option>
        </select> *@
        <br />
        <div class="form-group col-md-6">
        <input class="btn btn-dark" type="submit" />
        </div>
    </form>
</div>

        @if (Model != null)
        {
            @foreach (var job in Model)
            {

                
<div class="jobs">
    <br>
            <div class="card bg-light bg-gradient" style="width: 18rem; margin:2px;">
                <div class="cardbody" style="color: black;">
                    <h5 class="card-title list-group-item">@job.JobName</h5>
                    <p class="card-subtitle text-secondary">@job.Industry.Name</p>
                    <p class="card-text">Hourly Rate: @job.AvgWage/h</p>
                    
                </div>
                </div>
                </div>
                
            }
        }


<div>
    1   2   3   ...   >
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWMGApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SWMGApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 shadow-sm bg-dark">
            <div class="container-fluid">
                <a style="color:white;"class="navbar-brand">Job Discovery App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 bg-dark-subtle">
                        
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary btn-lg card p-3 shadow-sm" asp-area="" asp-controller="Home" asp-action="index">HomePage</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary btn-lg card p-3 shadow-sm" asp-area="" asp-controller="Jobs" asp-action="index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary btn-lg card p-3 shadow-sm" asp-area="" asp-controller="Data" asp-action="index">Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary btn-lg card p-3 shadow-sm" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> 
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SWMGApp - <a asp-area="" asp-controller="Home" asp-action="SWMG">About SWMG</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>